/* ============================================================
   Numidea Labs — project sheets.
   The page is complete static HTML (generated by scripts/build-scene.mjs).
   Language is handled by ../assets/page-i18n.js (shared with legal/);
   this file only opens captures in a viewer.
   ============================================================ */
(function () {
  /* image viewer: progressive — without JS (or <dialog>) the link opens the file */
  var dlg = document.getElementById('viewer');
  if (dlg && typeof dlg.showModal === 'function') {
    // created on first open: an <img> with no src counts as a broken image
    var big = null;
    document.addEventListener('click', function (ev) {
      var a = ev.target.closest && ev.target.closest('a.zoom');
      if (!a || ev.metaKey || ev.ctrlKey || ev.shiftKey) return;
      ev.preventDefault();
      var img = a.querySelector('img');
      if (!big) { big = document.createElement('img'); dlg.appendChild(big); }
      big.src = a.getAttribute('href');
      big.alt = img ? img.alt : '';
      dlg.classList.toggle('is-tall', !!(img && img.naturalHeight > img.naturalWidth));
      dlg.showModal();
    });
    dlg.addEventListener('click', function (ev) { if (ev.target === dlg || ev.target === big) dlg.close(); });
    dlg.addEventListener('close', function () { if (big) big.removeAttribute('src'); });
  }
})();
