/* ============================================================
   Numidea Labs — project sheets.
   The page is complete static HTML (generated by scripts/build-scene.mjs).
   This only does two things: switch FR / EN / AR (shared with the main
   site through localStorage) and open captures in a viewer.
   ============================================================ */
(function () {
  var dictEl = document.getElementById('i18n');
  var DICT = dictEl ? JSON.parse(dictEl.textContent) : null;
  var root = document.documentElement;

  function setLang(l) {
    if (!DICT || !DICT[l]) l = 'fr';
    var d = DICT[l];
    root.lang = l;
    root.dir = l === 'ar' ? 'rtl' : 'ltr';
    document.querySelectorAll('[data-i18n]').forEach(function (e) {
      var v = d[e.getAttribute('data-i18n')]; if (v != null) e.textContent = v;
    });
    document.querySelectorAll('[data-i18n-html]').forEach(function (e) {
      var v = d[e.getAttribute('data-i18n-html')]; if (v != null) e.innerHTML = v;
    });
    document.querySelectorAll('[data-i18n-alt]').forEach(function (e) {
      var v = d[e.getAttribute('data-i18n-alt')]; if (v != null) e.alt = v;
    });
    document.querySelectorAll('[data-i18n-aria]').forEach(function (e) {
      var v = d[e.getAttribute('data-i18n-aria')]; if (v != null) e.setAttribute('aria-label', v);
    });
    if (d['ui.title']) document.title = d['ui.title'];
    document.querySelectorAll('.lang button').forEach(function (b) {
      b.setAttribute('aria-pressed', String(b.getAttribute('data-lang') === l));
    });
    try { localStorage.setItem('numidea-lang', l); } catch (e) {}
  }

  var saved = 'fr';
  try { saved = localStorage.getItem('numidea-lang') || 'fr'; } catch (e) {}
  if (saved !== 'fr') setLang(saved);
  document.querySelectorAll('.lang button').forEach(function (b) {
    b.addEventListener('click', function () { setLang(b.getAttribute('data-lang')); });
  });

  /* image viewer: progressive — without JS (or <dialog>) the link opens the file */
  var dlg = document.getElementById('viewer');
  if (dlg && typeof dlg.showModal === 'function') {
    // created on first open: an <img> with no src counts as a broken image
    var big = null;
    document.addEventListener('click', function (ev) {
      var a = ev.target.closest && ev.target.closest('a.zoom');
      if (!a || ev.metaKey || ev.ctrlKey || ev.shiftKey) return;
      ev.preventDefault();
      var img = a.querySelector('img');
      if (!big) { big = document.createElement('img'); dlg.appendChild(big); }
      big.src = a.getAttribute('href');
      big.alt = img ? img.alt : '';
      dlg.classList.toggle('is-tall', !!(img && img.naturalHeight > img.naturalWidth));
      dlg.showModal();
    });
    dlg.addEventListener('click', function (ev) { if (ev.target === dlg || ev.target === big) dlg.close(); });
    dlg.addEventListener('close', function () { if (big) big.removeAttribute('src'); });
  }
})();
